#pragma once
//todo: sort these
#include "Core\Game.h"
#include "Core\GameObject.h"
#include "Core\Components\Component.h"
#include "Core\Components\ExtraComponentRegister.h"
#include "Physics\PhysicsEngine.h"
#include "Rendering\Core\Material.h"
#include "Core\Components\MeshRendererComponent.h"
#include "Core\Components\LightComponent.h"
#include "Core\Input.h"
#include "Core\Components\CameraComponent.h"
#include "Core\Assets\Scene.h"
#include "Rendering\Core\Camera.h"
#include "Core/Module/ModuleInterface.h"
#include "Core/Module/ModuleManager.h"
#include "Core/Assets/AssetTypes.h"
#include "Core/EngineInc.h"