#pragma once
#define NOMINMAX
#define GLM_FORCE_SWIZZLE
#include <glm/gtx/string_cast.hpp>
#include <glm\glm.hpp>
#include "include\glm\gtx\transform.hpp"
#include "include\glm\gtx\quaternion.hpp"
#include "include/glm/gtc/type_ptr.hpp"
#include <string>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <map>
#include <queue>
#include <algorithm>
#include <iostream>
#include <ios>
#include <memory.h>
#include <random>
#include "EngineGlobals.h"