#pragma once
#define NOMINMAX
#define GLM_FORCE_SWIZZLE
#include <glm/gtx/string_cast.hpp>
#include <glm\glm.hpp>
#include <string>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <vector>    
#include <map>
#include "EngineGlobals.h"