#pragma once
#include "glm\glm.hpp"
//#define WIN32_LEAN_AND_MEAN
//#include <Windows.h>
#include <string>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <GLEW\GL\glew.h>
#include <gl/glu.h>