#pragma once
class Light;
class GameObject;
class Shader_Depth;
class RHIBuffer;
class FrameBuffer;
class RHITextureArray;
class RHICommandList;
class Shader_Main;
class Camera;
class DeviceContext;
class RHITimeManager;
class RHIUAV;
class Mesh;
class ShaderProgramBase;
class BaseTexture;
template <class T> class IRHISharedDeviceObject;
template<class T> struct FrameCountingVector;
template<class T> class SharedPtr;
typedef SharedPtr<BaseTexture> BaseTextureRef;