#pragma once
class CameraComponent;
class ColliderComponent;
class MeshRendererComponent;
class Component;
class ParticleSystemComponent;
class LightComponent;
class RigidbodyComponent;
class ComponentRegistry;