#pragma once
#include "CameraComponent.h"
#include "ColliderComponent.h"
#include "MeshRendererComponent.h"
#include "Component.h"
#include "ParticleSystemComponent.h"
#include "LightComponent.h"
#include "RigidbodyComponent.h"
#include "ComponentRegistry.h"